name: Deploy Next.js to GitHub Pages

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout code
            uses: actions/checkout@v2
            
        -   name: Set working directory
            run: cd uobc-client

        -   name: Set up Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '18'

        -   name: Install dependencies
            working-directory: uobc-client
            run: npm install

        -   name: Build project
            working-directory: uobc-client
            run: npm run build

        -   name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: uobc-client/out
            
